### ISSUE TITLE
Display patient name at top of "Patient Records" view

### ISSUE THREAD

**Issue by mwytock0812** [nilbus/handoff#10]
When scrolling down, the patient's name is lost. Just as the user's name is displayed at the top, it would be useful if the patient's name is displayed on the topmost toolbar as the user scrolls.

Alternative solution: Allow the leftmost navigation pane float as the user scrolls.

**Comment by JYoung217** [comment]
I agree with this - I imagine this would be a fixed location when the user scrolls. Also, when you click on the links, it's nice that it takes you to the section you click on, but the navigation pane stays up top when it should move with you so that if you want to choose another section, you can do so quickly rather than go up to the top again.

**Comment by kylejmcintyre** [comment]
We planned that the nav bar on the left would be fixed during the scroll. We had this in at one point but it was causing another rendering issue. Now that we've agreed on the template, I'll revisit this.

**Comment by kylejmcintyre** [comment]
I believe I addressed your concerns as well as made a few other small improvements. Let me know if you agree.
